#!/bin/bash
# addpath : 스크립트 폴더를 PATH에 추가합니다.
echo "  "
echo "  "
echo "  $(tput setaf 3)Linux: PATH=~/script:\$PATH를 ~/.bashrc에 추가하십시오.$(tput sgr0)"
echo "  $(tput setaf 3)OS X:  PATH=~/script:\$PATH를 ~/.bash_profile에 추가하십시오.$(tput sgr0)"
echo "  $(tput setaf 3)source ~/.bashrc 혹은 ~/.bash_profile을 실행하십시오.$(tput sgr0)"
echo "  $(tput setaf 3)이제 어디서든 스크립트들을 사용할 수 있습니다.$(tput sgr0)"
echo "  "
echo "  "
