#!/bin/bash
# addpath : 스크립트 폴더를 PATH에 추가합니다.
echo "PATH=\$PATH:~/script" >> ~/.bashrc
cd ~
source .bashrc

# 결과 출력
echo "  "
echo "  $(tput setaf 3)~/script를 ~/.bashrc에 추가했습니다.$(tput sgr0)"
echo "  $(tput setaf 3)이제 어디서든 스크립트들을 사용할 수 있습니다.$(tput sgr0)"
echo "  "
