#!/bin/bash
# create [db_name] [user_name] [db_password]

# 데이터베이스를 생성합니다.
# 이미 같은 이름의 DB가 존재하면 생성하지 않습니다.

EXPECTED_ARGS=2
E_BADARGS=65
MYSQL=`which mysql`

Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="GRANT ALL ON $1.* TO '$2'@'localhost' IDENTIFIED BY '$3';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbname username dbpassword"
  exit $E_BADARGS
fi

echo "  $(tput setaf 3)DB를 만들기 위해 MySQL 비밀번호를 입력하세요.$(tput sgr0)"
$MYSQL -uroot -p -e "$SQL"
echo "  "
echo "  "
echo "  $(tput setaf 3)DB 생성$(tput sgr0): $(tput setaf 2)$1$(tput sgr0)"
echo "  "
echo "  "